-- OPflow · 1400 · Reference data: types of doctor, health problems, emergency kinds, health topics,
-- daily tips and the default app rules / kill switches.
-- GENERATED from app/lib/mock/data.dart and app/lib/mock/health.dart — keep them in step.
-- Health ARTICLES are not here: they are loaded as 'in_review' by the seed script and must be reviewed
-- by a doctor before they can be published (see the articles_published_reviewed constraint).

-- migrate:up

insert into doctor_types (id, simple_name, proper_name, icon, sort, is_common) values
  ('general', 'General doctor', 'General Medicine', 'medical_services_outlined', 1, true),
  ('child', 'Child doctor', 'Pediatrics', 'child_care', 2, true),
  ('women', 'Women''s doctor', 'Gynecology & Obstetrics', 'pregnant_woman', 3, true),
  ('skin', 'Skin doctor', 'Dermatology', 'face_retouching_natural', 4, true),
  ('bone', 'Bone doctor', 'Orthopedics', 'accessibility_new', 5, true),
  ('eye', 'Eye doctor', 'Ophthalmology', 'visibility_outlined', 6, true),
  ('ent', 'Ear-nose-throat doctor', 'ENT', 'hearing', 7, true),
  ('teeth', 'Teeth doctor', 'Dentistry', 'emoji_emotions_outlined', 8, true),
  ('heart', 'Heart doctor', 'Cardiology', 'favorite_border', 9, false),
  ('brain', 'Brain and nerve doctor', 'Neurology', 'psychology_outlined', 10, false),
  ('mind', 'Mind doctor', 'Psychiatry', 'self_improvement', 11, false),
  ('stomach', 'Stomach doctor', 'Gastroenterology', 'restaurant_outlined', 12, false),
  ('lungs', 'Lungs doctor', 'Pulmonology', 'air', 13, false),
  ('kidney', 'Urine and kidney doctor', 'Urology', 'water_drop_outlined', 14, false),
  ('surgeon', 'Surgeon', 'General Surgery', 'healing', 15, false);

insert into health_problems (id, name, icon, is_danger, sort) values
  ('fever', 'Fever', 'thermostat', false, 1),
  ('cough', 'Cough', 'masks_outlined', false, 2),
  ('cold', 'Cold / runny nose', 'ac_unit', false, 3),
  ('throat', 'Sore throat', 'record_voice_over_outlined', false, 4),
  ('headache', 'Headache', 'sick_outlined', false, 5),
  ('bodypain', 'Body pain', 'accessibility', false, 6),
  ('stomach', 'Stomach pain', 'restaurant_outlined', false, 7),
  ('vomiting', 'Vomiting', 'sick', false, 8),
  ('loose', 'Loose motions', 'wc', false, 9),
  ('constipation', 'Constipation', 'hourglass_bottom', false, 10),
  ('acidity', 'Acidity / burning chest', 'local_fire_department_outlined', false, 11),
  ('chest', 'Chest pain', 'favorite_border', true, 12),
  ('breathing', 'Breathing problem', 'air', true, 13),
  ('dizzy', 'Dizziness', 'cyclone', false, 14),
  ('joint', 'Joint pain', 'directions_walk', false, 15),
  ('back', 'Back pain', 'airline_seat_recline_normal', false, 16),
  ('rash', 'Skin rash', 'face_retouching_natural', false, 17),
  ('itching', 'Itching', 'back_hand_outlined', false, 18),
  ('pimples', 'Pimples', 'face', false, 19),
  ('hair', 'Hair fall', 'content_cut', false, 20),
  ('eyered', 'Red eyes', 'visibility_outlined', false, 21),
  ('eyepain', 'Eye pain', 'remove_red_eye_outlined', false, 22),
  ('ear', 'Ear pain', 'hearing', false, 23),
  ('tooth', 'Tooth pain', 'emoji_emotions_outlined', false, 24),
  ('urine', 'Urine problem', 'water_drop_outlined', false, 25),
  ('burning', 'Burning urine', 'local_fire_department', false, 26),
  ('periods', 'Periods problem', 'calendar_month_outlined', false, 27),
  ('pregnancy', 'Pregnancy', 'pregnant_woman', false, 28),
  ('fits', 'Fits (seizure)', 'bolt', true, 29),
  ('pregbleed', 'Bleeding in pregnancy', 'bloodtype_outlined', true, 30),
  ('worry', 'Stress / cannot sleep', 'nightlight_outlined', false, 31);

insert into problem_type_map (problem_id, type_id, audience, rank) values
  ('fever', 'general', 'adult', 1),
  ('fever', 'child', 'child', 1),
  ('cough', 'general', 'adult', 1),
  ('cough', 'lungs', 'adult', 2),
  ('cough', 'child', 'child', 1),
  ('cold', 'general', 'adult', 1),
  ('cold', 'ent', 'adult', 2),
  ('cold', 'child', 'child', 1),
  ('throat', 'ent', 'adult', 1),
  ('throat', 'general', 'adult', 2),
  ('throat', 'child', 'child', 1),
  ('throat', 'ent', 'child', 2),
  ('headache', 'general', 'adult', 1),
  ('headache', 'brain', 'adult', 2),
  ('headache', 'child', 'child', 1),
  ('bodypain', 'general', 'adult', 1),
  ('bodypain', 'child', 'child', 1),
  ('stomach', 'stomach', 'adult', 1),
  ('stomach', 'general', 'adult', 2),
  ('stomach', 'child', 'child', 1),
  ('vomiting', 'general', 'adult', 1),
  ('vomiting', 'stomach', 'adult', 2),
  ('vomiting', 'child', 'child', 1),
  ('loose', 'general', 'adult', 1),
  ('loose', 'stomach', 'adult', 2),
  ('loose', 'child', 'child', 1),
  ('constipation', 'stomach', 'adult', 1),
  ('constipation', 'general', 'adult', 2),
  ('constipation', 'child', 'child', 1),
  ('acidity', 'stomach', 'adult', 1),
  ('acidity', 'general', 'adult', 2),
  ('acidity', 'child', 'child', 1),
  ('chest', 'heart', 'adult', 1),
  ('chest', 'child', 'child', 1),
  ('breathing', 'lungs', 'adult', 1),
  ('breathing', 'general', 'adult', 2),
  ('breathing', 'child', 'child', 1),
  ('dizzy', 'general', 'adult', 1),
  ('dizzy', 'brain', 'adult', 2),
  ('dizzy', 'child', 'child', 1),
  ('joint', 'bone', 'adult', 1),
  ('joint', 'bone', 'child', 1),
  ('joint', 'child', 'child', 2),
  ('back', 'bone', 'adult', 1),
  ('back', 'bone', 'child', 1),
  ('rash', 'skin', 'adult', 1),
  ('rash', 'skin', 'child', 1),
  ('rash', 'child', 'child', 2),
  ('itching', 'skin', 'adult', 1),
  ('itching', 'skin', 'child', 1),
  ('itching', 'child', 'child', 2),
  ('pimples', 'skin', 'adult', 1),
  ('pimples', 'skin', 'child', 1),
  ('hair', 'skin', 'adult', 1),
  ('hair', 'skin', 'child', 1),
  ('eyered', 'eye', 'adult', 1),
  ('eyered', 'eye', 'child', 1),
  ('eyepain', 'eye', 'adult', 1),
  ('eyepain', 'eye', 'child', 1),
  ('ear', 'ent', 'adult', 1),
  ('ear', 'ent', 'child', 1),
  ('ear', 'child', 'child', 2),
  ('tooth', 'teeth', 'adult', 1),
  ('tooth', 'teeth', 'child', 1),
  ('urine', 'kidney', 'adult', 1),
  ('urine', 'general', 'adult', 2),
  ('urine', 'child', 'child', 1),
  ('burning', 'kidney', 'adult', 1),
  ('burning', 'general', 'adult', 2),
  ('burning', 'child', 'child', 1),
  ('periods', 'women', 'adult', 1),
  ('periods', 'women', 'child', 1),
  ('pregnancy', 'women', 'adult', 1),
  ('pregnancy', 'women', 'child', 1),
  ('fits', 'brain', 'adult', 1),
  ('fits', 'child', 'child', 1),
  ('pregbleed', 'women', 'adult', 1),
  ('pregbleed', 'women', 'child', 1),
  ('worry', 'mind', 'adult', 1),
  ('worry', 'mind', 'child', 1),
  ('worry', 'child', 'child', 2);

insert into emergency_kinds (id, name, detail, icon, sort) values
  ('child', 'Child is very sick', 'High fever, not feeding, breathing fast, fits', 'child_care', 1),
  ('heart', 'Chest pain / heart', 'Chest pain, heavy breathing, heart beating very fast', 'favorite', 2),
  ('accident', 'Accident or injury', 'Road accident, fall, broken bone, head injury, bleeding', 'personal_injury_outlined', 3),
  ('breathing', 'Breathing problem', 'Cannot breathe well, asthma attack', 'air', 4),
  ('brain', 'Fits or sudden weakness', 'Fits, one side weak, face drooping, not waking up', 'psychology_outlined', 5),
  ('pregnancy', 'Pregnancy problem', 'Bleeding, strong stomach pain, labour pain', 'pregnant_woman', 6),
  ('eye', 'Eye injury', 'Something went in the eye, chemical in eye, sudden loss of sight', 'visibility_outlined', 7),
  ('poison', 'Poison or snake bite', 'Swallowed poison, snake bite, dog bite', 'warning_amber_rounded', 8),
  ('other', 'Other urgent problem', 'Anything else that cannot wait', 'emergency_outlined', 9);

insert into emergency_kind_types (kind_id, type_id) values
  ('child', 'child'),
  ('heart', 'heart'),
  ('heart', 'general'),
  ('accident', 'bone'),
  ('accident', 'surgeon'),
  ('breathing', 'lungs'),
  ('breathing', 'general'),
  ('brain', 'brain'),
  ('brain', 'general'),
  ('pregnancy', 'women'),
  ('eye', 'eye'),
  ('poison', 'general'),
  ('poison', 'surgeon'),
  ('other', 'general');

insert into health_topics (id, name, icon, sort) values
  ('fever', 'Fever and infections', 'thermostat', 1),
  ('stomach', 'Stomach and water', 'water_drop_outlined', 2),
  ('children', 'Children', 'child_care', 3),
  ('women', 'Women and pregnancy', 'pregnant_woman', 4),
  ('season', 'Rain and summer', 'wb_sunny_outlined', 5),
  ('longterm', 'Sugar and BP', 'monitor_heart_outlined', 6),
  ('daily', 'Daily habits', 'self_improvement', 7);

insert into daily_tips (text) values
  ('Drink a glass of water when you wake up, and keep a bottle with you through the day.'),
  ('Wash your hands with soap for 20 seconds before eating and after using the toilet.'),
  ('Walk for 30 minutes today. Even two walks of 15 minutes help your heart.'),
  ('Once a week, empty water from coolers, pots and old tyres. Mosquitoes breed in still water.'),
  ('Take your BP or sugar tablets at the same time every day, even when you feel fine.'),
  ('Every 20 minutes on a screen, look at something far away for 20 seconds.'),
  ('Brush your teeth twice a day, for two minutes each time.'),
  ('Fill half your plate with vegetables and dal. Less rice, less oil, less salt.'),
  ('Sleep at the same time every night. Keep the phone away for the last half hour.'),
  ('Keep a packet of ORS at home. It saves lives when someone has loose motions.'),
  ('Keep your child''s vaccine card safe and take it to every visit.'),
  ('Feeling low for many days? Talk to someone you trust, or call Tele-MANAS on 14416.');

insert into app_config (key, value, description) values
  ('platform_fee_percent', '10'::jsonb, 'OPflow''s share of each consultation fee (the rest goes to the doctor)'),
  ('reschedule_cutoff_minutes', '120'::jsonb, 'Patients can change date or time up to this many minutes before their hour'),
  ('reschedule_max', '1'::jsonb, 'How many times a patient can change one booking'),
  ('hold_minutes', '10'::jsonb, 'How long a place is kept while the patient pays'),
  ('max_open_holds', '2'::jsonb, 'Open holds allowed per patient account'),
  ('payout_hold_hours', '24'::jsonb, 'Hours after the OPD session before the doctor''s 90% is released'),
  ('no_show_after_minutes', '60'::jsonb, 'Minutes after the patient''s hour before "did not come" is marked automatically'),
  ('move_pick_hours', '48'::jsonb, 'Hours a patient has to pick a new time after the doctor moves them'),
  ('min_supported_app_version', '"1.0.0"'::jsonb, 'Older apps see the "Please update OPflow" screen'),
  ('latest_app_version', '"1.0.0"'::jsonb, 'Older apps see a dismissible update banner'),
  ('bookings.enabled', 'true'::jsonb, 'Kill switch: new bookings'),
  ('payments.provider', '"razorpay"'::jsonb, 'Payment provider'),
  ('otp.provider', '"firebase"'::jsonb, 'Patient OTP provider (firebase or msg91)'),
  ('emergency.enabled', 'true'::jsonb, 'Kill switch: emergency help lists'),
  ('health_tips.enabled', 'true'::jsonb, 'Kill switch: health tips'),
  ('push.turn_alerts', 'true'::jsonb, 'Kill switch: "your turn is coming" pushes'),
  ('maintenance.message', 'null'::jsonb, 'When set, shown in the app as a maintenance notice');

-- migrate:down

delete from app_config;
delete from daily_tips;
delete from health_topics;
delete from emergency_kind_types;
delete from emergency_kinds;
delete from problem_type_map;
delete from health_problems;
delete from doctor_types;
