/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActorType = "admin" | "doctor" | "patient" | "system";

export type AdminRole = "content" | "finance" | "ops" | "super" | "support";

export type ApprovalDecision = "approved" | "expired" | "pending" | "rejected";

export type ApprovalKind = "admin_user_change" | "config_change" | "edit_doctor_locked" | "refund_large" | "suspend_doctor" | "verify_doctor";

export type ArticleStatus = "draft" | "in_review" | "published";

export type Audience = "adult" | "child";

export type BookingSource = "direct" | "emergency" | "online";

export type BookingStatus = "cancelled_by_provider" | "completed" | "confirmed" | "expired" | "no_show" | "pending_payment";

export type BulkKind = "cancel_day" | "end_opd_cancel" | "end_opd_move" | "move_day";

export type BulkStatus = "finished" | "needs_attention" | "running";

export type DevicePlatform = "android" | "ios" | "web";

export type DoctorStatus = "active" | "suspended";

export type DoctorVerification = "needs_correction" | "pending" | "rejected" | "verified";

export type DocumentKind = "degree" | "id_proof" | "other" | "registration";

export type EmergencyMode = "at_hospital" | "phone_first";

export type EmergencyState = "available_now" | "available_till" | "off" | "on_call";

export type Gender = "female" | "male" | "other";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type NotificationKind = "booked" | "cancelled" | "changed" | "late" | "refund" | "reminder" | "system" | "turn";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentStatus = "authorized" | "captured" | "created" | "failed";

export type PayoutStatus = "active" | "pending" | "suspended";

export type QueueState = "cancelled" | "did_not_come" | "done" | "moved" | "not_come" | "waiting" | "with_doctor";

export type RecordStatus = "active" | "hidden";

export type RefundReason = "admin_goodwill" | "duplicate" | "late_payment" | "provider_cancelled";

export type RefundStatus = "failed" | "pending" | "processed";

export type ReviewStatus = "approved" | "pending" | "rejected";

export type SessionStatus = "cancelled" | "ended" | "paused" | "running" | "scheduled";

export type SlotState = "blocked" | "booked" | "free" | "held";

export type TicketStatus = "answered" | "closed" | "open";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TransferStatus = "failed" | "on_hold" | "released" | "reversed";

export type UserRole = "admin" | "doctor" | "patient";

export type UserStatus = "active" | "deleted" | "suspended";

export type WindowStatus = "closed" | "open";

export interface AdminSetupTokens {
  adminId: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  tokenHash: Buffer;
  totpSecretEnc: Buffer;
  usedAt: Timestamp | null;
}

export interface PhoneOtps {
  attempts: Generated<number>;
  codeHash: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ip: string | null;
  phone: string;
  usedAt: Timestamp | null;
}

export interface AdminUsers {
  allowedIps: Generated<string[]>;
  createdAt: Generated<Timestamp>;
  email: string;
  failedAttempts: Generated<number>;
  id: Generated<string>;
  lastLoginAt: Timestamp | null;
  lockedUntil: Timestamp | null;
  name: string;
  passwordHash: string;
  role: AdminRole;
  status: Generated<UserStatus>;
  totpLastStep: Int8 | null;
  totpSecretEnc: Buffer | null;
  updatedAt: Generated<Timestamp>;
}

export interface AllowedTransitions {
  entity: string;
  fromState: string;
  toState: string;
}

export interface AppConfig {
  description: string | null;
  key: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
  value: Json;
}

export interface ApprovalRequests {
  decidedAt: Timestamp | null;
  decidedBy: string | null;
  decision: Generated<ApprovalDecision>;
  decisionNote: string | null;
  expiresAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: ApprovalKind;
  payload: Json;
  reason: string;
  requestedAt: Generated<Timestamp>;
  requestedBy: string;
  subjectId: string;
  subjectType: string;
}

export interface AuditLog {
  action: string;
  actorId: string | null;
  actorType: ActorType;
  after: Json | null;
  at: Generated<Timestamp>;
  before: Json | null;
  entity: string;
  entityId: string | null;
  id: Generated<Int8>;
  ip: string | null;
  requestId: string | null;
}

export interface BookingEvents {
  actorId: string | null;
  actorType: ActorType;
  at: Generated<Timestamp>;
  bookingId: string;
  data: Generated<Json>;
  id: Generated<Int8>;
  type: string;
}

export interface Bookings {
  cancelledAt: Timestamp | null;
  cancelledBy: string | null;
  cancelledReason: string | null;
  code: string;
  completedAt: Timestamp | null;
  confirmedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  doctorId: string;
  emergencyChargePaise: Generated<number>;
  feePaise: number;
  holdExpiresAt: Timestamp | null;
  hospitalId: string;
  id: Generated<string>;
  idempotencyKey: string | null;
  needsNewTimeSince: Timestamp | null;
  note: Generated<string>;
  patientAge: number | null;
  patientGender: Gender | null;
  patientName: string;
  patientUserId: string | null;
  platformFeePaise: Generated<number>;
  rescheduleCount: Generated<number>;
  rescheduledAt: Timestamp | null;
  sessionDate: string;
  sessionId: string;
  slotToken: Generated<number | null>;
  source: BookingSource;
  status: BookingStatus;
  token: number;
  updatedAt: Generated<Timestamp>;
  walkInPhone: string | null;
  windowId: string | null;
}

export interface BulkOperations {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  doctorId: string;
  done: Generated<number>;
  failed: Generated<number>;
  id: Generated<string>;
  kind: BulkKind;
  sessionId: string | null;
  status: Generated<BulkStatus>;
  total: number;
  updatedAt: Generated<Timestamp>;
}

export interface Devices {
  appVersion: string | null;
  createdAt: Generated<Timestamp>;
  fcmToken: string | null;
  id: Generated<string>;
  installId: string | null;
  lastSeenAt: Generated<Timestamp>;
  locale: string | null;
  platform: DevicePlatform;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DoctorCredentials {
  createdAt: Generated<Timestamp>;
  failedAttempts: Generated<number>;
  lockedUntil: Timestamp | null;
  loginId: string;
  mustChange: Generated<boolean>;
  passwordChangedAt: Timestamp | null;
  passwordHash: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DoctorDocuments {
  createdAt: Generated<Timestamp>;
  doctorId: string;
  fileKey: string;
  id: Generated<string>;
  kind: DocumentKind;
  note: string | null;
  reviewedAt: Timestamp | null;
  reviewedBy: string | null;
  status: Generated<ReviewStatus>;
}

export interface DoctorHospitals {
  createdAt: Generated<Timestamp>;
  doctorId: string;
  feePaiseOverride: number | null;
  hospitalId: string;
  isPrimary: Generated<boolean>;
  status: Generated<RecordStatus>;
}

export interface DoctorLeaves {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  date: string;
  doctorId: string;
  hospitalId: string | null;
  id: Generated<string>;
  reason: string | null;
}

export interface Doctors {
  about: Generated<string>;
  bookingsPaused: Generated<boolean>;
  bookingsPausedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdByAdmin: string | null;
  degrees: string;
  feePaise: number;
  gender: Gender;
  id: Generated<string>;
  languages: Generated<string[]>;
  listedAt: Timestamp | null;
  name: string;
  photoKey: string | null;
  regCouncil: string;
  regNo: string;
  searchVector: Generated<string | null>;
  status: Generated<DoctorStatus>;
  typeId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  verification: Generated<DoctorVerification>;
  verificationNote: string | null;
  verifiedAt: Timestamp | null;
  verifiedBy: string | null;
  yearsExperience: Generated<number>;
}

export interface DoctorTypes {
  icon: string;
  id: string;
  isCommon: Generated<boolean>;
  properName: string;
  simpleName: string;
  sort: Generated<number>;
}

export interface EmergencyKinds {
  detail: string;
  icon: string;
  id: string;
  name: string;
  sort: Generated<number>;
}

export interface EmergencyKindTypes {
  kindId: string;
  typeId: string;
}

export interface EmergencyStatus {
  doctorId: string;
  hospitalId: string | null;
  mode: Generated<EmergencyMode>;
  status: Generated<EmergencyState>;
  untilAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
}

export interface FirstAidGuides {
  callNowIf: string[];
  donts: string[];
  dos: string[];
  intro: string | null;
  kindId: string;
  locale: Generated<string>;
  publishedAt: Timestamp | null;
  reviewedAt: Timestamp | null;
  reviewedByDoctor: string | null;
  signs: Generated<string[]>;
  sources: Json;
  sourceToConfirm: Generated<boolean>;
  status: Generated<ArticleStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface HealthProblems {
  icon: string;
  id: string;
  isDanger: Generated<boolean>;
  name: string;
  sort: Generated<number>;
}

export interface HospitalDepartments {
  hospitalId: string;
  typeId: string;
}

export interface Hospitals {
  address: string;
  area: string;
  city: string;
  createdAt: Generated<Timestamp>;
  facadeSeed: Generated<number>;
  hasEmergency: Generated<boolean>;
  id: Generated<string>;
  lat: number;
  lng: number;
  name: string;
  opdTimingsText: string | null;
  phone: string;
  pin: string;
  search: Generated<string | null>;
  slug: string;
  status: Generated<RecordStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface IdempotencyKeys {
  createdAt: Generated<Timestamp>;
  key: string;
  requestHash: Buffer;
  response: Json | null;
  route: string;
  statusCode: number | null;
  userId: string;
}

export interface JobLeases {
  lastError: string | null;
  lastFinishedAt: Timestamp | null;
  lastStartedAt: Timestamp | null;
  lockedUntil: Generated<Timestamp>;
  name: string;
}

export interface NotificationPrefs {
  bookingChanges: Generated<boolean>;
  emailReceipts: Generated<boolean>;
  eveningSummary: Generated<boolean>;
  lateAlerts: Generated<boolean>;
  newBookings: Generated<boolean>;
  reminders: Generated<boolean>;
  turnAlerts: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Notifications {
  body: string;
  bookingId: string | null;
  createdAt: Generated<Timestamp>;
  data: Generated<Json>;
  dedupeKey: string | null;
  id: Generated<string>;
  kind: NotificationKind;
  readAt: Timestamp | null;
  title: string;
  userId: string;
}

export interface OpdSessions {
  avgConsultSec: Generated<number>;
  closeMinutesBefore: Generated<number>;
  createdAt: Generated<Timestamp>;
  date: string;
  doctorId: string;
  endedAt: Timestamp | null;
  endsAt: Timestamp;
  hospitalId: string;
  id: Generated<string>;
  lateMinutes: Generated<number>;
  nextEmergencyToken: Generated<number>;
  nowSeeingToken: number | null;
  startedAt: Timestamp | null;
  startsAt: Timestamp;
  status: Generated<SessionStatus>;
  templateId: string | null;
  updatedAt: Generated<Timestamp>;
  version: Generated<number>;
}

export interface OpdWindows {
  capacity: number;
  createdAt: Generated<Timestamp>;
  endsAt: Timestamp;
  id: Generated<string>;
  sessionId: string;
  startsAt: Timestamp;
  status: Generated<WindowStatus>;
  tokenStart: number;
  updatedAt: Generated<Timestamp>;
}

export interface Outbox {
  attempts: Generated<number>;
  availableAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  dedupeKey: string | null;
  doneAt: Timestamp | null;
  id: Generated<Int8>;
  lastError: string | null;
  payload: Json;
  topic: string;
}

export interface PatientProfiles {
  birthYear: number;
  createdAt: Generated<Timestamp>;
  gender: Gender;
  name: string;
  place: string | null;
  placeLat: number | null;
  placeLng: number | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Payments {
  abandoned: Generated<boolean>;
  amountPaise: number;
  bookingId: string;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  failureReason: string | null;
  id: Generated<string>;
  method: string | null;
  raw: Json | null;
  gatewayOrderId: string;
  gatewayPaymentId: string | null;
  status: Generated<PaymentStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface PayoutAccounts {
  bankLast4: string | null;
  createdAt: Generated<Timestamp>;
  doctorId: string;
  ifsc: string | null;
  beneficiaryId: string | null;
  status: Generated<PayoutStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface ProblemTypeMap {
  audience: Audience;
  problemId: string;
  rank: Generated<number>;
  typeId: string;
}

export interface QueueEntries {
  bookingId: string;
  calledAt: Timestamp | null;
  doneAt: Timestamp | null;
  orderKey: Numeric;
  reachedAt: Timestamp | null;
  sessionId: string;
  state: Generated<QueueState>;
  updatedAt: Generated<Timestamp>;
}

export interface QueueEvents {
  actorId: string | null;
  at: Generated<Timestamp>;
  bookingId: string | null;
  data: Generated<Json>;
  id: Generated<Int8>;
  sessionId: string;
  type: string;
  version: number;
}

export interface RefreshTokens {
  adminId: string | null;
  createdAt: Generated<Timestamp>;
  deviceId: string | null;
  expiresAt: Timestamp;
  familyId: string;
  id: Generated<string>;
  ip: string | null;
  replacedBy: string | null;
  revokedAt: Timestamp | null;
  role: UserRole | null;
  tokenHash: Buffer;
  userAgent: string | null;
  userId: string | null;
}

export interface Payouts {
  amountPaise: number;
  cfTransferId: string | null;
  createdAt: Generated<Timestamp>;
  deductedPaise: Generated<number>;
  doctorId: string;
  failureReason: string | null;
  id: Generated<string>;
  settledAt: Timestamp | null;
  status: Generated<'pending' | 'success' | 'failed'>;
  updatedAt: Generated<Timestamp>;
  utr: string | null;
  visitsPaise: number;
}

export interface Refunds {
  amountPaise: number;
  approvedBy: string | null;
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  failureReason: string | null;
  id: Generated<string>;
  initiatedBy: string | null;
  initiatedByType: ActorType;
  manualReference: string | null;
  nextAttemptAt: Timestamp | null;
  paymentId: string;
  gatewayRefundId: string | null;
  reason: RefundReason;
  status: Generated<RefundStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface ScheduleTemplates {
  avgConsultMinutes: Generated<number>;
  closeMinutesBefore: Generated<number>;
  createdAt: Generated<Timestamp>;
  doctorId: string;
  endMinute: Generated<number | null>;
  endTime: string;
  hospitalId: string;
  id: Generated<string>;
  onlinePerWindow: number;
  openDaysAhead: Generated<number>;
  startMinute: Generated<number | null>;
  startTime: string;
  takeEmergency: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  validFrom: Generated<string>;
  validTo: string | null;
  weekday: number;
  windowMinutes: Generated<number>;
}

export interface SupportTickets {
  assignedTo: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  message: string;
  requestId: string | null;
  status: Generated<TicketStatus>;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Transfers {
  amountPaise: number;
  createdAt: Generated<Timestamp>;
  doctorId: string;
  id: Generated<string>;
  paymentId: string;
  payoutId: string | null;
  recoveredIn: string | null;
  recoverPaise: Generated<number>;
  releaseAt: Timestamp;
  releasedAt: Timestamp | null;
  reversedAt: Timestamp | null;
  status: Generated<TransferStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface UserRoles {
  createdAt: Generated<Timestamp>;
  role: UserRole;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string | null;
  id: Generated<string>;
  lastLoginAt: Timestamp | null;
  phone: string | null;
  status: Generated<UserStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface WebhookEvents {
  error: string | null;
  id: string;
  payload: Json;
  processedAt: Timestamp | null;
  provider: Generated<string>;
  receivedAt: Generated<Timestamp>;
  type: string;
}

export interface WindowSlots {
  bookingId: string | null;
  heldUntil: Timestamp | null;
  state: Generated<SlotState>;
  token: number;
  updatedAt: Generated<Timestamp>;
  version: Generated<number>;
  windowId: string;
}

export interface DoctorPicks {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  doctorId: string;
  rank: Generated<number>;
  reasons: Generated<string[]>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface PickPurchases {
  amountPaise: number;
  consentAt: Timestamp;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  nearLat: number;
  nearLng: number;
  paidAt: Timestamp | null;
  patientUserId: string;
  place: string | null;
  gatewayOrderId: string;
  gatewayPaymentId: string | null;
  refundId: string | null;
  refundReason: string | null;
  refundedAt: Timestamp | null;
  result: Json | null;
  status: Generated<string>;
  typeId: string;
  updatedAt: Generated<Timestamp>;
}

export interface VisitFeedback {
  bookingId: string;
  createdAt: Generated<Timestamp>;
  doctorId: string;
  note: string | null;
  patientUserId: string;
  rating: number;
}

export interface DB {
  adminSetupTokens: AdminSetupTokens;
  adminUsers: AdminUsers;
  allowedTransitions: AllowedTransitions;
  appConfig: AppConfig;
  approvalRequests: ApprovalRequests;
  auditLog: AuditLog;
  bookingEvents: BookingEvents;
  bookings: Bookings;
  bulkOperations: BulkOperations;
  devices: Devices;
  doctorCredentials: DoctorCredentials;
  doctorDocuments: DoctorDocuments;
  doctorHospitals: DoctorHospitals;
  doctorLeaves: DoctorLeaves;
  doctors: Doctors;
  doctorTypes: DoctorTypes;
  emergencyKinds: EmergencyKinds;
  emergencyKindTypes: EmergencyKindTypes;
  emergencyStatus: EmergencyStatus;
  firstAidGuides: FirstAidGuides;
  healthProblems: HealthProblems;
  hospitalDepartments: HospitalDepartments;
  hospitals: Hospitals;
  idempotencyKeys: IdempotencyKeys;
  jobLeases: JobLeases;
  notificationPrefs: NotificationPrefs;
  notifications: Notifications;
  opdSessions: OpdSessions;
  opdWindows: OpdWindows;
  outbox: Outbox;
  patientProfiles: PatientProfiles;
  pickPurchases: PickPurchases;
  payments: Payments;
  payoutAccounts: PayoutAccounts;
  payouts: Payouts;
  phoneOtps: PhoneOtps;
  doctorPicks: DoctorPicks;
  visitFeedback: VisitFeedback;
  problemTypeMap: ProblemTypeMap;
  queueEntries: QueueEntries;
  queueEvents: QueueEvents;
  refreshTokens: RefreshTokens;
  refunds: Refunds;
  scheduleTemplates: ScheduleTemplates;
  supportTickets: SupportTickets;
  transfers: Transfers;
  userRoles: UserRoles;
  users: Users;
  webhookEvents: WebhookEvents;
  windowSlots: WindowSlots;
}
